### ISSUE TITLE
Continued Development?

### ISSUE THREAD

**Issue by jmreidy** [admc/wd#416]
Hey all - 

Firstly, I just want to say that wd.js is the most reliable JS webdriver implementation that I've used, especially for testing native apps with Appium. So - thanks for the work on this!

Kudos aside... WD's documentation is fairly abysmal. And there's a large number of open issues. I'm wondering if there could be a way of organizing community support of the library? It's obviously extraordinarily important to a great number of users! And I'm assuming it's blessed with Sauce's official support. 

I'd be happy to help in whatever way I can, and I'm sure other devs would be as well. Perhaps we could establish a priority list to triage the existing issues and documentation, and then go from there? I've gone ahead and created a Slack room to start - https://wd-js.slack.com

**Comment by sebv** [comment]
Hi,

The plan we have right know, although no official announcement has been made, is to merge WD.js into WebdriverIO. The main reason is that since WebdriverIO now use a A+  promise backed implementation both drivers have evolved to be very similar. 

It is easy to see that WebdriverIO has better documentation and better name. Also WD.js, has been written, in pure async code with some promise wrapper, and we've been wanting for a while to migrate it to pure promise, which I believe is exactly what webdriver.io does. Finally WD.js maintainer and WebdriverIO core maintainers both work for Sauce Labs, and spending time maintaining 2 drivers is not optimum, for us internally and for the community, we rather join the effort and make WebdriverIO as awesome as possible, and encourage contributors to do the same.

However we would like to do it without breaking the WD.js api (at least the promise one, we might spawn the async driver as a side project.). So the first stage would be to re-implement the WD.js api using WebdriverIO and then add some deprecation warnings.

I believe the Appium team has started to actively supporting both drivers, but WebdriverIO support is  recent so it might not yet be perfect.

@jlipps @christian-bromann any comment on that?

**Comment by sebv** [comment]
btw need an invite for the slack channel.

**Comment by jmreidy** [comment]
@sebv thanks for the clarification. I'm going to close this issue and simply migrate my tests to WebdriverIO. I had liked WD.js's chaining ability (passing elements through from one method call to the next - e.g. `waitForElement('id').setValue('val')` versus `waitForElement('id').setValue('id', 'val')` but that's not enough of a reason to NOT switch to WebdriverIO, and there may in fact be some value in taking away the "magic" of element chaining.

Thanks again on all the work from you and the Sauce team on making integration testing more of a breeze!

**Comment by christian-bromann** [comment]
@sebv @jmreidy I am not sure if we can ensure backwards compatibility to WD.js. The way WebdriverIO internally works is just too different. However I think switching to it should not be difficult. Updating all the mobile commands and make them easy to use will be the first step I want to do. After that I will see how I can make the migration from WD.js to WebdriverIO as easy as possible. Here are some major improvements I already see compared to WD.js:

WebdriverIO comes with:
- a build in test runner (called wdio) that takes a config file with capabilities, settings and spec files and runs them in parallel
- an cli configuration tool `$ wdio config` that helps you to generate your config file
- support for gulp and grunt
- a plugin called WebdriverCSS for visual regression testing (with Applitools integration)

In addition to that, the new major version (v4) will have support for sync commands. So if you using the testrunner you can write your commands in a synchronous way (see [example](https://github.com/webdriverio/webdriverio/blob/v4.0/examples/wdio/runner-specs/jasmine.spec.js)) whereas you are still able to integrate a promise workflow.

@jmreidy if you have any questions while migrating to WebdriverIO join the Gitter chat ([![Gitter](https://badges.gitter.im/Join Chat.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)) and ask me. I am available pretty much all the time to give support for everyone who has problems.

**Comment by sebv** [comment]
We could study how to add the chaining magic back to WebdriverIO, at least as an option, but yes this leads to more complicated use cases.
