### ISSUE TITLE
404 HTTP appium No route found

### ISSUE THREAD

**Issue by vladikstyle** [admc/wd#620]
Hey all,guys.Help me please . I try to repeat js script from there - 
https://github.com/dmlemeshko/appium/blob/master/docs/en/about-appium/getting-started.md
But have some issue and errors . Please help :) any solutions , all day trying (

![image](https://user-images.githubusercontent.com/62757817/77785689-39166c00-7065-11ea-963c-f681214313e4.png)
![image](https://user-images.githubusercontent.com/62757817/77785711-3ddb2000-7065-11ea-9171-a60e3ec21ecf.png)

**Comment by imurchie** [comment]
First, I would suggest using the official documentation (https://github.com/appium/appium/blob/master/docs/en/about-appium/getting-started.md) rather than a 2 year old fork of it.

Second, the documentation provided is for `webdriverio` (https://webdriver.io/) not `wd`.

Third, the issue is with the `path` configuration (http://v4.webdriver.io/guide/getstarted/configuration.html#path)
